#!/bin/bash

COURSE_DIR="WANKI/$1"

echo '-=-=-=-=- CARD LIST -=-=-=-=-'
cat -n $COURSE_DIR/flashcards.txt | sort
echo ''

echo 'Enter the question to go on the front of the card: '
read question 
echo 'Enter the answer to go on the back of the card: '
read answer
EXISTS=$(grep -i "$question | $answer" < $COURSE_DIR/flashcards.txt)
if [[  $EXISTS == "" ]]
then
    echo "$question | $answer" >> $COURSE_DIR/flashcards.txt
    echo "$question | $answer" >> $COURSE_DIR/again_flashcards.txt
else
    echo "Card already exists."
fi

echo
echo
echo '-=-=-=-=- UPDATED CARD LIST -=-=-=-=-'
cat -n $COURSE_DIR/flashcards.txt | sort
echo ''