#!/bin/bash
# Takes card deck and moves them all to standard difficulty setting ('again').
# Kaiden Jessani, McMaster University, 2024

COURSE_DIR="WANKI/$1"

# Prompt for reset input (only accept 'y')
echo "Are you SURE you want to reset all the difficulties? y/n"
read ans
if [[ $ans == 'y' ]]
then

    # Clear out all flash cards in other piles 
    echo -n > ${COURSE_DIR}/easy_flashcards.txt

    echo -n > ${COURSE_DIR}/hard_flashcards.txt

    echo -n > ${COURSE_DIR}/good_flashcards.txt

    echo -n > ${COURSE_DIR}/again_flashcards.txt

    # Move all flashcards into standard 'again' difficulty pile
    cat ${COURSE_DIR}/flashcards.txt > ${COURSE_DIR}/again_flashcards.txt

    echo "Difficulties reset"
    echo

else
    # Do nothing otherwise
    echo "Did not reset the card difficulties."
    echo
fi
